# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x86
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x86)
  Sockets_config = debug_x86
  Client_config = debug_x86
  Server_config = debug_x86
endif
ifeq ($(config),debug_x86_64)
  Sockets_config = debug_x86_64
  Client_config = debug_x86_64
  Server_config = debug_x86_64
endif
ifeq ($(config),release_x86)
  Sockets_config = release_x86
  Client_config = release_x86
  Server_config = release_x86
endif
ifeq ($(config),release_x86_64)
  Sockets_config = release_x86_64
  Client_config = release_x86_64
  Server_config = release_x86_64
endif

PROJECTS := Sockets Client Server

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Sockets:
ifneq (,$(Sockets_config))
	@echo "==== Building Sockets ($(Sockets_config)) ===="
	@${MAKE} --no-print-directory -C Sockets -f Makefile config=$(Sockets_config)
endif

Client: Sockets
ifneq (,$(Client_config))
	@echo "==== Building Client ($(Client_config)) ===="
	@${MAKE} --no-print-directory -C samples/Client-Server/Client -f Makefile config=$(Client_config)
endif

Server: Sockets
ifneq (,$(Server_config))
	@echo "==== Building Server ($(Server_config)) ===="
	@${MAKE} --no-print-directory -C samples/Client-Server/Server -f Makefile config=$(Server_config)
endif

clean:
	@${MAKE} --no-print-directory -C Sockets -f Makefile clean
	@${MAKE} --no-print-directory -C samples/Client-Server/Client -f Makefile clean
	@${MAKE} --no-print-directory -C samples/Client-Server/Server -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x86"
	@echo "  debug_x86_64"
	@echo "  release_x86"
	@echo "  release_x86_64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Sockets"
	@echo "   Client"
	@echo "   Server"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"